import tweepy #https://github.com/tweepy/tweepy
import pandas as pd
import csv
access_key = "695651038150266881-2iHmfIpodOhBCaxYndeFmQIucLouFRX"
access_secret = "SnZDYgPygKGdb8lqhPDgnIAhAIFpCUkZaSGtms7G8h1tP"
consumer_key = "jRPB3DWHBBEIiMNGTrywRN0UL"
consumer_secret = "iHHrFseYF5BEEByiRsQXhOQjqTC3teDNTZ2r8CIERmWUpFXLND"
#screen_name="JocoTheJacker"
def get_all_tweets(screen_name):
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_key, access_secret)
    api = tweepy.API(auth)
    alltweets = []	
    new_tweets = api.user_timeline(screen_name = screen_name,count=200)
    alltweets.extend(new_tweets)
    oldest = alltweets[-1].id - 1
    while len(new_tweets) > 0:
        print("getting tweets before %s" % (oldest))
        new_tweets = api.user_timeline(screen_name = screen_name,count=200,max_id=oldest)
        alltweets.extend(new_tweets)
        oldest = alltweets[-1].id - 1
        print("...%s tweets downloaded so far" % (len(alltweets)))
    outtweets = [[tweet.id_str, tweet.created_at, tweet.text.encode("utf-8")] for tweet in alltweets]
    dataframe=pd.DataFrame(outtweets,columns=['twitter_id','date','tweet'])
    dataframe.to_csv("%s_.csv"%(screen_name),index=False)

if __name__ == '__main__':
	#pass in the username of the account you want to download
    get_all_tweets("JocoTheJacker")
    get_all_tweets("SamLipworth")
    get_all_tweets("liamhanninen")
    get_all_tweets("AfeezAziz")
    get_all_tweets("milou1p")
    get_all_tweets("___Gianluca____")
    get_all_tweets("dhakalneil")
    get_all_tweets("fkling42")
    get_all_tweets("danielroseman")
    get_all_tweets("fredrikredin")
    get_all_tweets("puf")
    get_all_tweets("anubhava")
    get_all_tweets("pthivent")
    get_all_tweets("billkarwin")
    get_all_tweets("rmayoff")
    get_all_tweets("basarat")
    get_all_tweets("Nick_Craver")
    get_all_tweets("PeterLawrey")
    get_all_tweets("MatterOfFact")
    get_all_tweets("lassevk")
    get_all_tweets("MoVonLagos")
    get_all_tweets("klmr")
    get_all_tweets("rmm5t")
    get_all_tweets("mhl20")
    get_all_tweets("markwragg")
    get_all_tweets("mureinik")
    get_all_tweets("ericlippert")
    get_all_tweets("phihag")
    get_all_tweets("jwmittag")
    get_all_tweets("darkestspirit")
    get_all_tweets("memon_md_farhan")
    get_all_tweets("DietrichEpp")
    get_all_tweets("GabMarioPower")
    get_all_tweets("brianbondy")
    get_all_tweets("tnurkiewicz")
    get_all_tweets("jrotenstein")
    get_all_tweets("edalorzo")
    get_all_tweets("ReedCopsey")
    get_all_tweets("JamesMcNellis")
    get_all_tweets("karim79")
    get_all_tweets("puredanger")
    get_all_tweets("gprussell")
    get_all_tweets("_tieppt")
    get_all_tweets("spickermann")
    get_all_tweets("ploeh")
    get_all_tweets("cocoaphony")
    get_all_tweets("phley")
    get_all_tweets("drewag")
    get_all_tweets("gregbacon")
    get_all_tweets("jxxf")
    get_all_tweets("DeborahKurata")
    get_all_tweets("pkanavos")
    get_all_tweets("lukaseder")
    get_all_tweets("dcsobral")
    get_all_tweets("imanoupetit")
    get_all_tweets("AlexSikilinda")
    get_all_tweets("BinaryMuse")
    get_all_tweets("pniederw")
    get_all_tweets("LuchianGrig")
    get_all_tweets("ashajjar85")
    get_all_tweets("mrozekma")
    get_all_tweets("SeaRyanC")
    get_all_tweets("JustinPihony")
    get_all_tweets("thomaslevesque")
    get_all_tweets("mtopolnik")
    get_all_tweets("paullebeau")
    get_all_tweets("agud")
    get_all_tweets("artem_bilan")
    get_all_tweets("cgoldberg")
    get_all_tweets("Berlyant")
    get_all_tweets("adamquek99")
    get_all_tweets("ErRaviubana")
    get_all_tweets("goloroden")
    get_all_tweets("dirvo")
    get_all_tweets("pareshmayani")
    get_all_tweets("tzachzohar")
    get_all_tweets("bdoughan")
    get_all_tweets("joshua_ulrich")
    get_all_tweets("gabro27")
    get_all_tweets("mrdesjardins")
    get_all_tweets("AdamBellaire")
    get_all_tweets("sebastienlorber")
    get_all_tweets("pfourie")
    get_all_tweets("lennartregebro")
    get_all_tweets("anon38527")
    get_all_tweets("tylerrinker")
    get_all_tweets("derarthur")
    get_all_tweets("james_allardice")
    get_all_tweets("DanielHilgarth")
    get_all_tweets("downwind")
    get_all_tweets("alexjlockwood")
    get_all_tweets("simeonvisser")
    get_all_tweets("shlomme")
    get_all_tweets("ankinson")
    get_all_tweets("Avalanche1979")
    get_all_tweets("inkarkat")
    get_all_tweets("meineerde")
    get_all_tweets("ashleymgrant")
    get_all_tweets("tapasthakkar")
    get_all_tweets("rtoal")
    get_all_tweets("Raynos")
    get_all_tweets("gkadillak")
